### ISSUE TITLE
Rethink about the runtime process model and electron

### ISSUE THREAD

**Issue by Yukaii** [BlastLauncher/blast#30]
I have some difficulties starting the application shipping process around commit fb29964ff9f47ccdb877a4a827abae9357682005.

Initially, I started the runtime in electron's [utility process](https://www.electronjs.org/docs/latest/api/utility-process) and struggled with packager bundling 2fcb790682b53b21e8f984f6f7dd054b1d201e26. Eventually, I found it too troublesome to eval/load the extension module and its dependencies inside the electron main process, so I decided to manage the Node.js binary on the user's computer and run the runtime with that nodejs runtime.

Regarding the shipping of the runtime, currently I use `esbuild` to build another single file cjs module of blast-runtime. I have two options:

- Use that downloaded node binary's npm to install `@blastlauncher/runtime` with `~/.blast/extensions` prefix, just like other blast-extensions. The version can be explicitly found in `~/.blast/extensions/package.json`, and version pinning and upgrading can also be easily done.
- Ship the runtime module as electron assets. We can bundle it with electron-forge's webpack, and there's no need to handle some spawn process magic. But it needs to be upgraded with the electron app itself.

About the compatibility between the runtime and frontend, it's another story.

### Tasks

- [x] Update the `@blastlauncher/runtime` package to include minimum runtime dependencies. All deps should be bundled with esbuild.
- ~~Publish a new version of runtime.~~ Use it along and pack with electron-client module webpack
- [x] Implement a node binary manager module in `@blastlauncher/utils` (We can search for an existing solution first).
- [x] Integrate the node binary manager in the electron-client.
- [x] Implement a runtime process manager in the electron-client.

**Comment by Yukaii** [comment]
- https://stackoverflow.com/questions/62405815/loading-nodejs-module-at-runtime-in-electron-app
- https://github.com/davideicardi/live-plugin-manager

**Comment by Yukaii** [comment]
- Bundle `blast-runtime/run.cjs` along with electron app

https://github.com/ganeshrvel/tutorial-electron-bundle-binaries/
